---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
In stature the Manlet was dwarfish–

No burly, big Blunderbore he;

And he wearily gazed on the crawfish

His Wifelet had dressed for his tea.

’Now reach me, sweet Atom, my gunlet,

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I’ve been fighting a War Within Myself all my life,

Tired of the hurt, the pain, the strife.

Anger consumes me from day to day,

Cellies now walking on eggshells, unsure of what to

say.

I do pray each night for the peace that I need in my

heart,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
“The sun was shining on the sea,
  Shining with all his might:
  

He did his very best to make
  The billows smooth and bright —
  

And this was odd, because it was
  The middle of the night.

The moon was shining sulkily,
  Because she thought the sun
  

Had got no business to be there
  After the day was done —
  

“It’s very rude of him,” she said,
  "To come and spoil the fun."

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
You are the sunlight in my day

You are the moon I see far away

You are the one I lean upon

You are the one who makes my troubles gone

You are the one who taught me life

how not to fight and the difference between right

and wrong

You are the words within my song

You are my wonderful MOM

You are the one who cares for me

You are the eyes that help me see

You are the one who knows me best

You are my favorite from east to west

You are the one who helped me dream

You hear my heart

You hear me scream

I’m afraid of life but looking for love

I’m blessed that God sent me you from above

You are my friend, my heart, and soul

You are the greatest MOM I know
